### ISSUE TITLE
carousel is not working for upgraded flutter in my project.Do anyone can help me......?

### ISSUE THREAD

**Issue by sortie** [gbrvalerio/carousel#11]
_From @ranjannisha on September 10, 2018 9:7_

URL: https://pub.dartlang.org/packages/carousel
I upgraded my flutter today and got an issue 
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because breadfruit depends on carousel >=0.1.0 which requires SDK version <2.0.0, version solving failed.

_Copied from original issue: dart-lang/pub-dartlang-dart#1593_

**Comment by brammittendorff** [comment]
This should be fixed now, can you try it again?
https://github.com/gbrvalerio/carousel/pull/12

**Comment by jediyeti** [comment]
> This should be fixed now, can you try it again?
> #12

For me still not working.
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

**Comment by brammittendorff** [comment]
@jediyeti Did you try adding carousel in the `pubspec.yml` as:
```
  carousel:
    git:
      url: git://github.com/gbrvalerio/carousel.git
```

This will make sure you got the latest version with the update on pubspec.yml

**Comment by toureholder** [comment]
@brammittendorff 

>   carousel:
>     git:
>       url: git://github.com/gbrvalerio/carousel.git
> ```

Didn't solve it for me. Just tried it and got:

The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because my_app depends on carousel any which requires SDK version <2.0.0, version solving failed.
pub upgrade failed (1)

**Comment by brammittendorff** [comment]
Did you try `dependency_overrides` already?
https://github.com/flutter/flutter/issues/21599

```
dependency_overrides:
  carousel: "^0.1.0"
```

**Comment by toureholder** [comment]
> Did you try `dependency_overrides` already?
> [flutter/flutter#21599](https://github.com/flutter/flutter/issues/21599)
> 
> ```
> dependency_overrides:
>   carousel: "^0.1.0"
> ```

it works with this :)

**Comment by jediyeti** [comment]
> @jediyeti Did you try adding carousel in the `pubspec.yml` as:
> 
> ```
>   carousel:
>     git:
>       url: git://github.com/gbrvalerio/carousel.git
> ```
> This will make sure you got the latest version with the update on pubspec.yml

This helped! Working even without `dependency_overrides:`
